spring:
  application:
    name: web
logging:
  level:
    root: debug
  config: classpath:log4j2.xml

server:
  port: 8988
---
management:
  endpoints:
    web:
#      base-path: /ac
      exposure:
        include: '*'
  info:
    env:
      enabled: true
---
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
        # 这里不配置server端会报错，未知的主机错误
        instance:
          service-url: http://localhost:8088
  jmx:
    enabled: true
---
spring:
  security:
    user:
      name: admin
      password: admin123
      roles:
        - USER
        - MGR
---
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
        instance:
          service-url: http://localhost:8088
        username: admin
        password: admin123
---
server: # 内嵌tomcat access log配置 和 打开 tomcat mbean 方式
  tomcat:
    basedir: "spring-boot-web"
    accesslog:
        enabled: true
        pattern: '%{yyyy-MM-dd HH:mm:ss}t %a %A %m %s %D %b %I %U%q %{User-Agent}i'
    mbeanregistry:
      enabled: true
